version: '3.1'

services:
    app:
        build: .
        container_name: lampa-backend-boilerplate
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - mongo
        volumes:
            - data:/app/data/app
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: adminadmin
        ports:
            - '27017:27017'
        volumes:
            - data:/app/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: adminadmin
            ME_CONFIG_MONGODB_URL: mongodb://admin:adminadmin@mongo:27017/
volumes:
    data:
