/auth/login:
    post:
        tags: [Auth]
        summary: Login a user
        description: Login a user
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            email:
                                type: string
                                required: true
                                example: 'vasya@gmail.com'
                                description: User's email
                            password:
                                type: string
                                required: true
                                example: 'vasyavasya'
                                description: User's password
        responses:
            200:
                description: Access and refresh tokens
/auth/register:
    post:
        tags: [Auth]
        summary: Register a user
        description: Register a user
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            email:
                                type: string
                                required: true
                                example: 'vasya@gmail.com'
                                description: User's email
                            password:
                                type: string
                                required: true
                                example: 'vasyavasya'
                                description: User's password
        responses:
            200:
                description: Access and refresh tokens
/auth/refresh-token:
    post:
        tags: [Auth]
        summary: Refresh tokens
        description: Refresh tokens
        requestBody:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            refreshToken:
                                type: string
                                required: true
                                example: 'afadfadasdsdfsdfsd'
                                description: User's refresh token
                            userId:
                                type: string
                                required: true
                                example: '123'
                                description: User Id
        responses:
            200:
                description: Access and refresh tokens
